import { createSlice } from '@reduxjs/toolkit';

// A slice is a function from toolkit that combines the functionality
// of an action and a reducer into one
const codeSlice = createSlice({
  name: "codeSlice",
  initialState: {
    codeState: false,
    mode: "css",
  },

  // actions are auto-generated by the creation of the reducers
  reducers: {
    toggleCode(state, action) { state.codeState = !state.codeState },
    setMode(state, action) { state.mode = action.payload },
  }
});

export const { toggleCode, setMode } = codeSlice.actions;
export default codeSlice.reducer;
