import { createSlice } from '@reduxjs/toolkit';

// A slice is a function from toolkit that combines the functionality
// of an action and a reducer into one
const importSlice = createSlice({
  name: "importSlice",
  initialState: {
    importState: false,
  },

  // actions are auto-generated by the creation of the reducers
  reducers: {
    toggleImport(state, action) { state.importState = !state.importState },
  }
});

export const { toggleImport } = importSlice.actions;
export default importSlice.reducer;
