import { createSlice } from '@reduxjs/toolkit';

// A slice is a function from toolkit that combines the functionality
// of an action and a reducer into one
const loadSlice = createSlice({
  name: "loadSlice",
  initialState: {
    loadState: false,
    components: [],
  },

  // actions are auto-generated by the creation of the reducers
  reducers: {
    toggleLoad(state, action) { state.loadState = !state.loadState },
    setComponents(state, action) { state.components = action.payload },
  }
});

export const { toggleLoad, setComponents } = loadSlice.actions;
export default loadSlice.reducer;
