import { createSlice } from '@reduxjs/toolkit';

// A slice is a function from toolkit that combines the functionality
// of an action and a reducer into one
const menuSlice = createSlice({
  name: "menuSlice",
  initialState: {
    menuState: false,
  },

  // actions are auto-generated by the creation of the reducers
  reducers: {
    toggleMenu(state, action) { state.menuState = !state.menuState },
  }
});

export const { toggleMenu } = menuSlice.actions;
export default menuSlice.reducer;
