import { createSlice } from '@reduxjs/toolkit';

// A slice is a function from toolkit that combines the functionality
// of an action and a reducer into one
const userSlice = createSlice({
  name: "userSlice",
  initialState: {
    currentUser: null,
    users: [],
  },

  // actions are auto-generated by the creation of the reducers
  reducers: {
    setUsers(state, action) { state.users = action.payload },
    setUser(state, action) { state.currentUser = action.payload },
  }
});

export const { setUser, setUsers } = userSlice.actions;
export default userSlice.reducer;
