import { createSlice } from '@reduxjs/toolkit';

const currentUser = null;

// A slice is a function from toolkit that combines the functionality
// of an action and a reducer into one
const userSlice = createSlice({
  name: "userSlice",
  initialState: {
    currentUser,
    users: [],
  },

  // actions are auto-generated by the creation of the reducers
  reducers: {
    setUsers(state, action) { state.users = action.payload },
    setUser(state, action) { state.currentUser = action.payload },
    resetUser(state, action) { state.currentUser = currentUser }
  }
});

export const { setUser, setUsers, resetUser } = userSlice.actions;
export default userSlice.reducer;
