import { createSlice } from '@reduxjs/toolkit';

// A slice is a function from toolkit that combines the functionality
// of an action and a reducer into one
const saveSlice = createSlice({
  name: "saveSlice",
  initialState: {
    saveFormState: false,
  },

  // actions are auto-generated by the creation of the reducers
  reducers: {
    toggleSaveForm(state, action) { state.saveFormState = !state.saveFormState },
  }
});

export const { toggleSaveForm } = saveSlice.actions;
export default saveSlice.reducer;
